-- specs/046-subgroup-requirement-checklist.
--
-- What each document sub-group is supposed to hold, and whether it does.
--
-- หมวด 6 became a submission checklist: the officer asks for specific documents
-- and each sub-group exists to hold a particular set of them. The folder name
-- cannot say which ones, an empty folder says nothing at all, and a full one can
-- still be wrong (the SUZUYO test reports). Until now that knowledge lived in a
-- Google Doc regenerated by hand.
--
-- Applied by hand in the Supabase SQL Editor — there is no DDL path from the
-- app's machine. The app tolerates this migration being absent (research
-- Decision 4), so deploying the code first is safe. Idempotent: safe to re-run.

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

alter table document_categories add column if not exists description text;
alter table document_groups add column if not exists description text;

create table if not exists document_group_requirements (
  id uuid primary key default gen_random_uuid(),
  -- Items describe what a folder should hold; they are not documents, so they
  -- go with their sub-group rather than blocking its deletion (FR-015).
  group_id uuid not null references document_groups (id) on delete cascade,
  name_th text not null check (btrim(name_th) <> ''),
  status text not null default 'missing' check (status in ('have', 'missing', 'waiting')),
  note text,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists document_group_requirements_group_idx
  on document_group_requirements (group_id, sort_order);

alter table document_group_requirements enable row level security;

-- Same shape as every other table: the real authorization is the
-- requireRole("editor") check in the Server Actions, not RLS.
drop policy if exists "authenticated full access document_group_requirements" on document_group_requirements;
create policy "authenticated full access document_group_requirements" on document_group_requirements
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ---------------------------------------------------------------------------
-- Initial content for หมวด 6 — the spec appendix, checked against every file's
-- contents on 2026-09-17. lib/requirement-seed.test.ts requires these rows to
-- match the appendix exactly (SC-002).
--
-- Safe to run again (FR-018):
--   * a description is only written where it is still empty, so editing it in
--     the app afterwards is never overwritten;
--   * a sub-group's items are only inserted when it has none, so nothing is
--     duplicated and nothing an editor changed is reset;
--   * sub-groups are matched by exact name inside checklist-permit — one renamed
--     or removed since the audit matches nothing and is skipped, rather than its
--     items landing somewhere they do not belong.
-- ---------------------------------------------------------------------------

with category_wording (description) as (values ('ชุดเอกสารสำหรับยื่นขออนุญาตระบบความปลอดภัยอาคารต่อเจ้าพนักงานท้องถิ่น จัดเรียงตาม checklist ที่เจ้าหน้าที่ขอ ไฟล์ในหมวดนี้เป็นสำเนาที่คัดมาจากหมวด 1-5 ต้นฉบับยังอยู่ในหมวดเดิมเสมอ'))
update document_categories c
set description = category_wording.description
from category_wording
where c.slug = 'checklist-permit'
  and c.description is null;

with group_wording (name_th, description) as (values
  ('ใบอนุญาต อ.1 และ อ.5', 'ใบอนุญาตดัดแปลงอาคาร (อ.1) และใบรับรองการใช้อาคาร (อ.5)'),
  ('ใบรับรองตามกฎหมาย', 'หนังสือรับรองที่กฎหมายบังคับสำหรับคลังวัตถุอันตราย'),
  ('แบบแผนงานส่วนต่อเติม', 'แบบก่อสร้างส่วนที่ดัดแปลงและต่อเติม แบบระบบป้องกันฟ้าผ่า และผลวัดพื้นกันไฟฟ้าสถิต'),
  ('ผังการจัดวางอุปกรณ์ดูดซับและถังทราย', 'ผังและหลักฐานการวางอุปกรณ์ดูดซับสารเคมีและถังทรายแห้งในแต่ละห้อง'),
  ('ใบรับรองและสเปก', 'ใบรับรองผลิตภัณฑ์และสเปกชีทของวัสดุอุปกรณ์ที่ติดตั้งจริง'),
  ('ทดสอบ', 'ผลทดสอบระบบของอาคารนี้ และผลทดสอบทนไฟของวัสดุจากห้องปฏิบัติการ'),
  ('องศาความลาดเอียงพื้นอาคาร', 'ค่าความลาดเอียงของพื้นอาคาร'),
  ('มิติและปริมาตรบ่อรับน้ำเสีย', 'ขนาดกว้าง ยาว ลึก และปริมาตรของบ่อรับน้ำเสียและบ่อพักน้ำ'),
  ('ข้อมูลรางระบายน้ำ', 'แนว ขนาด และความลาดเอียงของรางน้ำภายในและภายนอกโกดัง'),
  ('ระยะและเส้นทแยงมุมห้องแรก', 'ระยะที่วัดจริงและเส้นทแยงมุมของห้องแรก'),
  ('แผนผังโครงการและโกดัง', 'แบบอาคาร ผัง Layout โกดัง และแผนงาน พร้อมตำแหน่งอุปกรณ์ความปลอดภัย'),
  ('เส้นทางขนส่งสารเคมี', 'แผนผังโครงการแสดงเส้นทางขนส่งสารเคมีเข้าและออก')
)
update document_groups g
set description = group_wording.description
from group_wording, document_categories c
where g.category_id = c.id
  and c.slug = 'checklist-permit'
  and g.name_th = group_wording.name_th
  and g.description is null;

with seed_items (group_name, position, name_th, status, note) as (values
  ('ใบอนุญาต อ.1 และ อ.5', 1, 'อ.1 ใบอนุญาตดัดแปลงอาคาร พร้อมใบเสร็จค่าธรรมเนียม', 'have', 'เลขที่ 22/2569 ออก 25 ม.ค. 2569 — ต้องรายงานความคืบหน้าทุก 90 วัน'),
  ('ใบอนุญาต อ.1 และ อ.5', 2, 'อ.5 ใบรับรองการใช้อาคาร', 'missing', null),
  ('ใบรับรองตามกฎหมาย', 1, 'หนังสือรับรองบุคลากรเฉพาะความปลอดภัยการเก็บวัตถุอันตราย (บฉ.4)', 'have', 'เลขที่ บฉ69-0439'),
  ('แบบแผนงานส่วนต่อเติม', 1, 'แบบดัดแปลงอาคารโครงสร้างเหล็ก 1 ชั้น ชุดเต็ม', 'have', '12 แผ่น ไฟล์อยู่ในหมวดย่อย แผนผังโครงการและโกดัง'),
  ('แบบแผนงานส่วนต่อเติม', 2, 'แผนงาน Gantt ดัดแปลงอาคาร', 'have', 'ไฟล์อยู่ในหมวดย่อย แผนผังโครงการและโกดัง'),
  ('แบบแผนงานส่วนต่อเติม', 3, 'แบบแผนระบบป้องกันฟ้าผ่า (หัวล่อฟ้า สายนำลง หลักดิน)', 'missing', null),
  ('แบบแผนงานส่วนต่อเติม', 4, 'ใบรายงานผลตรวจวัดค่าความต้านทาน (โอห์ม) ของพื้นกันไฟฟ้าสถิต', 'waiting', 'รอทำสายล่อฟ้าเสร็จก่อน'),
  ('ผังการจัดวางอุปกรณ์ดูดซับและถังทราย', 1, 'ผังระบุตำแหน่งอุปกรณ์ดูดซับและถังทรายแห้ง', 'missing', 'ผัง Layout โกดัง 01 ไม่มีสัญลักษณ์ของสองอย่างนี้'),
  ('ผังการจัดวางอุปกรณ์ดูดซับและถังทราย', 2, 'รูปถ่ายหลักฐานการจัดวางหน้างาน', 'missing', null),
  ('ใบรับรองและสเปก', 1, 'สเปกพัดลมกันระเบิด ระบุยี่ห้อและรุ่น', 'have', 'Chatwanee BPS-60'),
  ('ใบรับรองและสเปก', 2, 'คำนวณปริมาณลมผ่านเกล็ดระบายอากาศ (Louver)', 'have', 'ลงนามวิศวกร ภย.42738'),
  ('ใบรับรองและสเปก', 3, 'สเปก ใบรับรอง และใบรับประกันแผ่นหลังคาและผนัง', 'have', 'Zincalume / Colorbond, MiT, ใบรับประกัน TH-26-06-PG025-060'),
  ('ใบรับรองและสเปก', 4, 'สเปกและใบอนุญาต มอก. แผ่นยิปซัมทนไฟ', 'have', 'TOA, มอก.219-2566'),
  ('ใบรับรองและสเปก', 5, 'สเปกโคมไฟกันระเบิด', 'have', 'Emergency Light, Exit Light, High Bay'),
  ('ใบรับรองและสเปก', 6, 'ใบรับรององศาการกระจายหัวสปริงเกลอร์ — ส่วนตู้สายม้วน', 'missing', null),
  ('ใบรับรองและสเปก', 7, 'ใบรับรอง (Certificate) Emergency Shower', 'missing', null),
  ('ใบรับรองและสเปก', 8, 'เอกสารสเปก Emergency Shower', 'missing', null),
  ('ใบรับรองและสเปก', 9, 'สเปกทั่วไปของประตูม้วน', 'missing', 'มีแต่ผลทดสอบทนไฟ FSRC-028/66'),
  ('ใบรับรองและสเปก', 10, 'ระบบปลดล็อกด้วยมือกรณีไฟฟ้าดับ (ประตูม้วน)', 'missing', null),
  ('ใบรับรองและสเปก', 11, 'ข้อมูลจำเพาะหลังคากรงนก', 'missing', 'Zincalume / Colorbond เป็นแผ่นหลังคาและผนัง ไม่ใช่หลังคากรงนก'),
  ('ทดสอบ', 1, 'ผลทดสอบระบบแจ้งเหตุเพลิงไหม้', 'have', 'ตรวจ 1 ก.ย. 2569 โดย ภฟก.52065'),
  ('ทดสอบ', 2, 'ผลทดสอบทนไฟผนังยิปซัม ประตูเหล็ก และประตูม้วน', 'have', 'FSRC จุฬาฯ'),
  ('ทดสอบ', 3, 'ผลดันเทสระบบสปริงเกลอร์ ของอาคารนี้', 'missing', 'เอกสาร V.T.S. และการคำนวณไฮดรอลิกที่มีเป็นของ SUZUYO ใช้ยื่นแทนไม่ได้'),
  ('ทดสอบ', 4, 'ผลดันเทสตู้สายดับเพลิง ของอาคารนี้', 'missing', 'ภาพทดสอบที่มีเป็นของ SUZUYO ใช้ยื่นแทนไม่ได้'),
  ('ทดสอบ', 5, 'ผลทดสอบระบบไฟฟ้า / การเชื่อมต่อ ลงนามโดยวิศวกรผู้มีใบอนุญาต', 'missing', null),
  ('ทดสอบ', 6, 'ผลเทสระบบเพิ่มเติมตามบันทึกประชุม', 'missing', 'ยังไม่ระบุว่าระบบใด'),
  ('องศาความลาดเอียงพื้นอาคาร', 1, 'ค่าความลาดเอียงพื้น', 'have', 'แปลนพื้น 1:100 ระบุ 1% ทุกจุด — เป็นค่าตามแบบ ไม่ใช่ค่าที่วัดหน้างาน'),
  ('มิติและปริมาตรบ่อรับน้ำเสีย', 1, 'มิติบ่อรับน้ำเสีย 2 ช่อง', 'have', '41.2×9.10×1.12 ม. และ 4.85×9.0×1.12 ม.'),
  ('มิติและปริมาตรบ่อรับน้ำเสีย', 2, 'มิติบ่อพักน้ำประจำแต่ละห้อง', 'have', '1.00×1.00×2.00 ม.'),
  ('มิติและปริมาตรบ่อรับน้ำเสีย', 3, 'ยืนยันปริมาตรความจุรวม', 'missing', 'ภาพมิติได้ประมาณ 468.8 ลบ.ม. แต่บันทึกประชุมระบุประมาณ 200 ลบ.ม.'),
  ('มิติและปริมาตรบ่อรับน้ำเสีย', 4, 'แบบมิติบ่อที่ลงนามโดยผู้ออกแบบหรือผู้วัด', 'missing', 'ไฟล์ที่มีเป็นภาพประกอบ ไม่มีลายเซ็น'),
  ('มิติและปริมาตรบ่อรับน้ำเสีย', 5, 'รูปถ่ายบ่อจริง', 'missing', null),
  ('ข้อมูลรางระบายน้ำ', 1, 'ผังแนวลำรางรองรับสารเคมีหกรั่วไหลและบ่อพัก', 'have', null),
  ('ข้อมูลรางระบายน้ำ', 2, 'ขนาดกว้าง ยาว รางน้ำภายในโกดัง', 'missing', 'ผังที่มีบอกแนวราง แต่ไม่มีขนาด'),
  ('ข้อมูลรางระบายน้ำ', 3, 'ระดับความลาดเอียง (สโลป) ของราง', 'missing', null),
  ('ข้อมูลรางระบายน้ำ', 4, 'ขนาดรางน้ำภายนอกโกดัง', 'missing', null),
  ('ระยะและเส้นทแยงมุมห้องแรก', 1, 'ตัวเลขระยะที่วัดจากประตูของห้องแรก', 'missing', null),
  ('ระยะและเส้นทแยงมุมห้องแรก', 2, 'เส้นทแยงมุมห้องแรก', 'missing', 'ผังที่มาร์กด้วยมือก่อนหน้าได้ประมาณ 39.13 และ 38.16 ม. เทียบเกณฑ์ "น้อยกว่า 35 ม." — ควรยืนยันกับวิศวกร'),
  ('แผนผังโครงการและโกดัง', 1, 'ผัง Layout ตำแหน่ง Smoke Detector และ Manual push alarm', 'have', 'ผลทดสอบระบุ Smoke 46 ตัว, Manual pull 6 จุด'),
  ('แผนผังโครงการและโกดัง', 2, 'ผัง Layout ทิศทางเปิดประตู', 'have', null),
  ('แผนผังโครงการและโกดัง', 3, 'ผัง Layout ตำแหน่งอ่างล้างตา (wash station)', 'have', null),
  ('แผนผังโครงการและโกดัง', 4, 'บันทึกชี้แจงว่าไม่มีเครื่องตรวจจับก๊าซ', 'missing', null),
  ('แผนผังโครงการและโกดัง', 5, 'ผัง Layout ฉบับที่ออกและลงนามโดยผู้ออกแบบ', 'missing', 'ฉบับที่มีทำใน Canva ไม่มีตารางชื่อแบบหรือลายเซ็น'),
  ('แผนผังโครงการและโกดัง', 6, 'การตรวจหน้างานว่าประตูเปิดตรงตาม layout จริง', 'missing', null),
  ('เส้นทางขนส่งสารเคมี', 1, 'แผนผังเส้นทางขนส่งสารเคมีเข้า-ออก', 'have', 'มาตราส่วน 1:700')
)
insert into document_group_requirements (group_id, name_th, status, note, sort_order)
select g.id, seed_items.name_th, seed_items.status, seed_items.note, seed_items.position
from seed_items
join document_groups g on g.name_th = seed_items.group_name
join document_categories c on c.id = g.category_id and c.slug = 'checklist-permit'
where not exists (select 1 from document_group_requirements r where r.group_id = g.id)
order by g.id, seed_items.position;
